# Generated by Django 5.0.6 on 2024-06-26 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extracciones', '0001_initial'),
        ('obstetra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCurvaLarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('cita_curva_larga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracciones.curvalarga')),
                ('usuaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoExtracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('cita_extracciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracciones.citaextracciones')),
                ('usuaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoObstetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('cita_obstetra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetra.citaobstetra')),
                ('usuaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
