# Generated by Django 5.0.6 on 2024-06-26 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMatrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0),
                                                                              django.core.validators.MaxValueValidator(200.0)])),
                ('altura', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0),
                                                                                django.core.validators.MaxValueValidator(2.0)])),
                ('imc', models.FloatField(blank=True, null=True)),
                ('tas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0),
                                                                               django.core.validators.MaxValueValidator(300)])),
                ('tad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0),
                                                                                django.core.validators.MaxValueValidator(200)])),
                ('trimestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('orden', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1),
                                                                                 django.core.validators.MaxValueValidator(2)])),
                ('exploracion_obstetrica', models.CharField(blank=True, max_length=255, null=True)),
                ('egb', models.BooleanField(blank=True, default=False, null=True)),
                ('usuaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
